#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : traefik
Version  : 2.4.5
Release  : 26
URL      : https://github.com/traefik/traefik/archive/v2.4.5/traefik-2.4.5.tar.gz
Source0  : https://github.com/traefik/traefik/archive/v2.4.5/traefik-2.4.5.tar.gz
Source1  : http://localhost/cgit/projects/traefik-vendor/snapshot/traefik-vendor-2.4.5.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause CC-BY-SA-4.0 ISC MIT MPL-2.0 MPL-2.0-no-copyleft-exception
Requires: traefik-bin = %{version}-%{release}
Requires: traefik-data = %{version}-%{release}
Requires: traefik-license = %{version}-%{release}
Requires: traefik-services = %{version}-%{release}
BuildRequires : buildreq-golang
Patch1: 0001-Switch-to-just-building-the-traefik-binary.patch

%description
<p align="center">
<img src="docs/content/assets/img/traefik.logo.png" alt="Traefik" title="Traefik" />
</p>

%package bin
Summary: bin components for the traefik package.
Group: Binaries
Requires: traefik-data = %{version}-%{release}
Requires: traefik-license = %{version}-%{release}
Requires: traefik-services = %{version}-%{release}

%description bin
bin components for the traefik package.


%package data
Summary: data components for the traefik package.
Group: Data

%description data
data components for the traefik package.


%package license
Summary: license components for the traefik package.
Group: Default

%description license
license components for the traefik package.


%package services
Summary: services components for the traefik package.
Group: Systemd services

%description services
services components for the traefik package.


%prep
%setup -q -n traefik-2.4.5
cd %{_builddir}
tar xf %{_sourcedir}/traefik-vendor-2.4.5.tar.xz
cd %{_builddir}/traefik-2.4.5
mkdir -p vendor
cp -r %{_builddir}/traefik-vendor-2.4.5/* %{_builddir}/traefik-2.4.5/vendor
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1613700315
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1613700315
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/traefik
cp %{_builddir}/traefik-2.4.5/LICENSE.md %{buildroot}/usr/share/package-licenses/traefik/b610f9367f8cbc6221c6c9319caf09ab07786268
cp %{_builddir}/traefik-2.4.5/docs/content/assets/js/hljs/LICENSE %{buildroot}/usr/share/package-licenses/traefik/cd25196630fe891662ad77810f0f6dee5bc85ddc
cp %{_builddir}/traefik-vendor-2.4.5/cloud.google.com/go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Azure/azure-sdk-for-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/861181924d993ee58a17a2c3c3a3faecf895849c
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Azure/go-ansiterm/LICENSE %{buildroot}/usr/share/package-licenses/traefik/836ef1b46953afdb78ce3929bc6831ca83620b65
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Azure/go-autorest/autorest/LICENSE %{buildroot}/usr/share/package-licenses/traefik/308c47a3ea356402d2d14241da9a9f64cf404008
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Azure/go-autorest/autorest/adal/LICENSE %{buildroot}/usr/share/package-licenses/traefik/308c47a3ea356402d2d14241da9a9f64cf404008
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Azure/go-autorest/autorest/azure/auth/LICENSE %{buildroot}/usr/share/package-licenses/traefik/308c47a3ea356402d2d14241da9a9f64cf404008
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Azure/go-autorest/autorest/azure/cli/LICENSE %{buildroot}/usr/share/package-licenses/traefik/308c47a3ea356402d2d14241da9a9f64cf404008
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Azure/go-autorest/autorest/date/LICENSE %{buildroot}/usr/share/package-licenses/traefik/308c47a3ea356402d2d14241da9a9f64cf404008
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Azure/go-autorest/autorest/to/LICENSE %{buildroot}/usr/share/package-licenses/traefik/308c47a3ea356402d2d14241da9a9f64cf404008
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Azure/go-autorest/autorest/validation/LICENSE %{buildroot}/usr/share/package-licenses/traefik/308c47a3ea356402d2d14241da9a9f64cf404008
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Azure/go-autorest/logger/LICENSE %{buildroot}/usr/share/package-licenses/traefik/308c47a3ea356402d2d14241da9a9f64cf404008
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Azure/go-autorest/tracing/LICENSE %{buildroot}/usr/share/package-licenses/traefik/308c47a3ea356402d2d14241da9a9f64cf404008
cp %{_builddir}/traefik-vendor-2.4.5/github.com/BurntSushi/toml/COPYING %{buildroot}/usr/share/package-licenses/traefik/f9cab757896ef6b3570e62b2df7fb63ab1a34b80
cp %{_builddir}/traefik-vendor-2.4.5/github.com/DataDog/datadog-go/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/2028422a9ed73d6afc856a46f41ff4207f4aed8d
cp %{_builddir}/traefik-vendor-2.4.5/github.com/ExpediaDotCom/haystack-client-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/12e48afc2b1eb5db59385d6b9b207f462a0fb271
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Masterminds/goutils/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Masterminds/semver/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/19faac93bab978326d06e3b96bbf41d495ce2a51
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Masterminds/semver/v3/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/020acfcf6d6bd6d701d19bd16f49d0bf18441779
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Masterminds/sprig/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/239eb7b8270d659c1316e04c7081921142226198
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Masterminds/sprig/v3/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/535e3badf5b532d842627b504976fbb93bc2d8b8
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Microsoft/go-winio/LICENSE %{buildroot}/usr/share/package-licenses/traefik/11a8fec351554e8f6c3f4dac5a1f4049dd467ba8
cp %{_builddir}/traefik-vendor-2.4.5/github.com/Microsoft/hcsshim/LICENSE %{buildroot}/usr/share/package-licenses/traefik/56b820712432e458f05f883566ca8cd85dcdaad5
cp %{_builddir}/traefik-vendor-2.4.5/github.com/OpenDNS/vegadns2client/LICENSE %{buildroot}/usr/share/package-licenses/traefik/21b9019f7aa793ffcba310799b9909430c426839
cp %{_builddir}/traefik-vendor-2.4.5/github.com/PuerkitoBio/purell/LICENSE %{buildroot}/usr/share/package-licenses/traefik/33cd8e150548e595fbe201c6ca9df582976e71db
cp %{_builddir}/traefik-vendor-2.4.5/github.com/PuerkitoBio/urlesc/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7f7a12bcfc16fab2522aa1a562fd3d2aee429d3b
cp %{_builddir}/traefik-vendor-2.4.5/github.com/VividCortex/gohistogram/LICENSE %{buildroot}/usr/share/package-licenses/traefik/e0bb5df1969ef7b428077d4a2441d81678ec4846
cp %{_builddir}/traefik-vendor-2.4.5/github.com/abbot/go-http-auth/LICENSE %{buildroot}/usr/share/package-licenses/traefik/04319952ed7b0f3b3a70ae4d5d9f954317b8f970
cp %{_builddir}/traefik-vendor-2.4.5/github.com/abronan/valkeyrie/LICENSE.code %{buildroot}/usr/share/package-licenses/traefik/fb1bf49ddf574b8e6d1863539b1a08ec3b66d05e
cp %{_builddir}/traefik-vendor-2.4.5/github.com/abronan/valkeyrie/LICENSE.docs %{buildroot}/usr/share/package-licenses/traefik/979fd7d5c67073b265d96f584aac3de1c419b8e2
cp %{_builddir}/traefik-vendor-2.4.5/github.com/akamai/AkamaiOPEN-edgegrid-golang/LICENSE %{buildroot}/usr/share/package-licenses/traefik/92170cdc034b2ff819323ff670d3b7266c8bffcd
cp %{_builddir}/traefik-vendor-2.4.5/github.com/aliyun/alibaba-cloud-sdk-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/904db295d780f20aeb75042f236708b28edcdfc1
cp %{_builddir}/traefik-vendor-2.4.5/github.com/armon/go-metrics/LICENSE %{buildroot}/usr/share/package-licenses/traefik/5d06409981dfdb6c13963148f9a18c5c3eaac4fe
cp %{_builddir}/traefik-vendor-2.4.5/github.com/armon/go-radix/LICENSE %{buildroot}/usr/share/package-licenses/traefik/96e730c77952892784bebe06fd42b297b67ea06e
cp %{_builddir}/traefik-vendor-2.4.5/github.com/aws/aws-sdk-go/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/aws/aws-sdk-go/internal/sync/singleflight/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d6a5f1ecaedd723c325a2063375b3517e808a2b5
cp %{_builddir}/traefik-vendor-2.4.5/github.com/beorn7/perks/LICENSE %{buildroot}/usr/share/package-licenses/traefik/b2e4520feb0f9b51ad373256b94c3faf4c1e6871
cp %{_builddir}/traefik-vendor-2.4.5/github.com/boombuler/barcode/LICENSE %{buildroot}/usr/share/package-licenses/traefik/9a42583034b13e145f6c077b013f1f27da13c1d9
cp %{_builddir}/traefik-vendor-2.4.5/github.com/cenkalti/backoff/v4/LICENSE %{buildroot}/usr/share/package-licenses/traefik/101c182fa18fd56a09164278f17e4282264c5e9e
cp %{_builddir}/traefik-vendor-2.4.5/github.com/cespare/xxhash/v2/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/7be82c1a81e7197640a88df91dc82d64b77c7acd
cp %{_builddir}/traefik-vendor-2.4.5/github.com/cloudflare/cloudflare-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/0c84bd26de8694ce5b00eedec272769f22a5538c
cp %{_builddir}/traefik-vendor-2.4.5/github.com/codahale/hdrhistogram/LICENSE %{buildroot}/usr/share/package-licenses/traefik/23d68de7aa2faedcbe131e4ff5b1fdd25af585dd
cp %{_builddir}/traefik-vendor-2.4.5/github.com/containerd/containerd/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d3b7a70b03b43d4e7205d178100581923a0baad2
cp %{_builddir}/traefik-vendor-2.4.5/github.com/containerd/continuity/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d3b7a70b03b43d4e7205d178100581923a0baad2
cp %{_builddir}/traefik-vendor-2.4.5/github.com/containous/alice/LICENSE %{buildroot}/usr/share/package-licenses/traefik/34b266cae5bba7e3b33a080c3d328f9aa598e806
cp %{_builddir}/traefik-vendor-2.4.5/github.com/coreos/etcd/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/coreos/go-systemd/LICENSE %{buildroot}/usr/share/package-licenses/traefik/172ca3bbafe312a1cf09cfff26953db2f425c28e
cp %{_builddir}/traefik-vendor-2.4.5/github.com/cpu/goacmedns/LICENSE %{buildroot}/usr/share/package-licenses/traefik/78d6de13df5ab04962a5301b2fa08e6da55f1aba
cp %{_builddir}/traefik-vendor-2.4.5/github.com/davecgh/go-spew/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d2f340a01dd48b589a70f627cf7058c585a315e4
cp %{_builddir}/traefik-vendor-2.4.5/github.com/dgrijalva/jwt-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/b132e03c6b6bd85fbc2394f808acae8f5d0ebaf0
cp %{_builddir}/traefik-vendor-2.4.5/github.com/dimchansky/utfbom/LICENSE %{buildroot}/usr/share/package-licenses/traefik/92170cdc034b2ff819323ff670d3b7266c8bffcd
cp %{_builddir}/traefik-vendor-2.4.5/github.com/dnsimple/dnsimple-go/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/4e969f5760ada4247efca2e282cd450b5df37f9a
cp %{_builddir}/traefik-vendor-2.4.5/github.com/docker/cli/LICENSE %{buildroot}/usr/share/package-licenses/traefik/878e7d86573d6c8ff65d2eaab294734b3f4d3d81
cp %{_builddir}/traefik-vendor-2.4.5/github.com/docker/cli/NOTICE %{buildroot}/usr/share/package-licenses/traefik/5476f2f91673ef040f1956907e7f45e72d5e11ee
cp %{_builddir}/traefik-vendor-2.4.5/github.com/docker/distribution/LICENSE %{buildroot}/usr/share/package-licenses/traefik/c700a8b9312d24bdc57570f7d6a131cf63d89016
cp %{_builddir}/traefik-vendor-2.4.5/github.com/docker/docker-credential-helpers/LICENSE %{buildroot}/usr/share/package-licenses/traefik/f3eab54cb1736b419ef75b8c44bea2b17614bd31
cp %{_builddir}/traefik-vendor-2.4.5/github.com/docker/docker/LICENSE %{buildroot}/usr/share/package-licenses/traefik/20b06a68cf65738d43afa04acce0126f341c77f8
cp %{_builddir}/traefik-vendor-2.4.5/github.com/docker/docker/NOTICE %{buildroot}/usr/share/package-licenses/traefik/5476f2f91673ef040f1956907e7f45e72d5e11ee
cp %{_builddir}/traefik-vendor-2.4.5/github.com/docker/docker/pkg/symlink/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/traefik/de6aabbb551ff752e690d7a1136a5b5228f130cb
cp %{_builddir}/traefik-vendor-2.4.5/github.com/docker/docker/pkg/symlink/LICENSE.BSD %{buildroot}/usr/share/package-licenses/traefik/818cd8d3934fc2af85e81c1f39c51ef7f661c139
cp %{_builddir}/traefik-vendor-2.4.5/github.com/docker/go-connections/LICENSE %{buildroot}/usr/share/package-licenses/traefik/3110e55750143a84918d7423febc9c83a55bc28c
cp %{_builddir}/traefik-vendor-2.4.5/github.com/docker/go-metrics/LICENSE %{buildroot}/usr/share/package-licenses/traefik/376caa2cd54c4196280157d071524614350e7ce8
cp %{_builddir}/traefik-vendor-2.4.5/github.com/docker/go-metrics/LICENSE.docs %{buildroot}/usr/share/package-licenses/traefik/979fd7d5c67073b265d96f584aac3de1c419b8e2
cp %{_builddir}/traefik-vendor-2.4.5/github.com/docker/go-units/LICENSE %{buildroot}/usr/share/package-licenses/traefik/3110e55750143a84918d7423febc9c83a55bc28c
cp %{_builddir}/traefik-vendor-2.4.5/github.com/docker/libcompose/LICENSE %{buildroot}/usr/share/package-licenses/traefik/34554dbd133157d01181d9849768152d3c68149e
cp %{_builddir}/traefik-vendor-2.4.5/github.com/eapache/channels/LICENSE %{buildroot}/usr/share/package-licenses/traefik/4278180522ac398eca5a90de73b4f29a4e9aef82
cp %{_builddir}/traefik-vendor-2.4.5/github.com/eapache/queue/LICENSE %{buildroot}/usr/share/package-licenses/traefik/aee2763a63c10c110c21f1942cf8e3187009148c
cp %{_builddir}/traefik-vendor-2.4.5/github.com/elastic/go-sysinfo/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/elastic/go-windows/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/elazarl/go-bindata-assetfs/LICENSE %{buildroot}/usr/share/package-licenses/traefik/3ad128f30b382b49f591245750c269076248de2b
cp %{_builddir}/traefik-vendor-2.4.5/github.com/emicklei/go-restful/LICENSE %{buildroot}/usr/share/package-licenses/traefik/a8993f4a51771a0333dbbc5b1c4395a2ccaa4d9f
cp %{_builddir}/traefik-vendor-2.4.5/github.com/evanphx/json-patch/LICENSE %{buildroot}/usr/share/package-licenses/traefik/17c7cd81bb03c410ed4fb4859c3caf55d16e8cab
cp %{_builddir}/traefik-vendor-2.4.5/github.com/exoscale/egoscale/LICENSE %{buildroot}/usr/share/package-licenses/traefik/267ef34592bbf4b90c2aee662050e00de8aab9a6
cp %{_builddir}/traefik-vendor-2.4.5/github.com/fatih/structs/LICENSE %{buildroot}/usr/share/package-licenses/traefik/5473ed979e3291e2de03eb43700bf4953b1bb7ae
cp %{_builddir}/traefik-vendor-2.4.5/github.com/felixge/httpsnoop/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/d3d30f733d36ea721eb89e9c37f899f729a0ea5e
cp %{_builddir}/traefik-vendor-2.4.5/github.com/flynn/go-shlex/COPYING %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/gambol99/go-marathon/LICENSE %{buildroot}/usr/share/package-licenses/traefik/f0b513a735cc88cc1f37c5ee0caec2a9e154bd86
cp %{_builddir}/traefik-vendor-2.4.5/github.com/go-acme/lego/v4/LICENSE %{buildroot}/usr/share/package-licenses/traefik/8ac28139bb1d105323e9ec990b68488edcf427fd
cp %{_builddir}/traefik-vendor-2.4.5/github.com/go-check/check/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7280d51677a5550c328b89f3db1f5e87427f2533
cp %{_builddir}/traefik-vendor-2.4.5/github.com/go-errors/errors/LICENSE.MIT %{buildroot}/usr/share/package-licenses/traefik/a1b4279f3ae16b42693f03c8c610df15a32f02da
cp %{_builddir}/traefik-vendor-2.4.5/github.com/go-kit/kit/LICENSE %{buildroot}/usr/share/package-licenses/traefik/c6ad24467b71e3c84eb2d73dffb7fd168e203c4a
cp %{_builddir}/traefik-vendor-2.4.5/github.com/go-logfmt/logfmt/LICENSE %{buildroot}/usr/share/package-licenses/traefik/ec2d07fe9c52f1a0cb319e200c30d4e40045ad37
cp %{_builddir}/traefik-vendor-2.4.5/github.com/go-logr/logr/LICENSE %{buildroot}/usr/share/package-licenses/traefik/92170cdc034b2ff819323ff670d3b7266c8bffcd
cp %{_builddir}/traefik-vendor-2.4.5/github.com/go-openapi/jsonpointer/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/go-openapi/jsonreference/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/go-openapi/spec/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/go-openapi/spec/license.go %{buildroot}/usr/share/package-licenses/traefik/555e9ac61d94352b3c2935e77b51fc6dc31d4822
cp %{_builddir}/traefik-vendor-2.4.5/github.com/go-openapi/swag/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/go-resty/resty/v2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/c3449b45ed5b8824cf5973495f72bf4b2370f46f
cp %{_builddir}/traefik-vendor-2.4.5/github.com/gofrs/uuid/LICENSE %{buildroot}/usr/share/package-licenses/traefik/b4b35a8138ee83256aca752d3813d3d0757d8380
cp %{_builddir}/traefik-vendor-2.4.5/github.com/gogo/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/traefik/06b27345acae9303e13dde9974d2b2e318b05989
cp %{_builddir}/traefik-vendor-2.4.5/github.com/golang/groupcache/LICENSE %{buildroot}/usr/share/package-licenses/traefik/172ca3bbafe312a1cf09cfff26953db2f425c28e
cp %{_builddir}/traefik-vendor-2.4.5/github.com/golang/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/traefik/aa9b240f558caed367795f667629ccbca28f20b2
cp %{_builddir}/traefik-vendor-2.4.5/github.com/google/go-cmp/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7080652cc78cd9855d39e324529a3b5f3745dcd6
cp %{_builddir}/traefik-vendor-2.4.5/github.com/google/go-github/v28/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d80a2259c41a1be1d07366c4df5d2edf3afede27
cp %{_builddir}/traefik-vendor-2.4.5/github.com/google/go-querystring/LICENSE %{buildroot}/usr/share/package-licenses/traefik/5d833085cd09e0a70fe9071b1f2edf6d31b91d45
cp %{_builddir}/traefik-vendor-2.4.5/github.com/google/gofuzz/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/google/uuid/LICENSE %{buildroot}/usr/share/package-licenses/traefik/08021ae73f58f423dd6e7b525e81cf2520f7619e
cp %{_builddir}/traefik-vendor-2.4.5/github.com/googleapis/gax-go/v2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2bda142bd58fd76f408cf18fa997d8fab0278a22
cp %{_builddir}/traefik-vendor-2.4.5/github.com/googleapis/gnostic/LICENSE %{buildroot}/usr/share/package-licenses/traefik/5a7d7df655ba40478fae80a6abafc6afc36f9b6a
cp %{_builddir}/traefik-vendor-2.4.5/github.com/gophercloud/gophercloud/LICENSE %{buildroot}/usr/share/package-licenses/traefik/01e537267fca176b08cd25a4e6e6a7092ed3c734
cp %{_builddir}/traefik-vendor-2.4.5/github.com/gophercloud/utils/LICENSE %{buildroot}/usr/share/package-licenses/traefik/92170cdc034b2ff819323ff670d3b7266c8bffcd
cp %{_builddir}/traefik-vendor-2.4.5/github.com/gorilla/context/LICENSE %{buildroot}/usr/share/package-licenses/traefik/417483c9ccd2847921fd8605edf02b5a243b4761
cp %{_builddir}/traefik-vendor-2.4.5/github.com/gorilla/mux/LICENSE %{buildroot}/usr/share/package-licenses/traefik/417483c9ccd2847921fd8605edf02b5a243b4761
cp %{_builddir}/traefik-vendor-2.4.5/github.com/gorilla/websocket/LICENSE %{buildroot}/usr/share/package-licenses/traefik/307711a68aa375a23d90191db6f720426cf88402
cp %{_builddir}/traefik-vendor-2.4.5/github.com/gravitational/trace/LICENSE %{buildroot}/usr/share/package-licenses/traefik/702efc433d30e282422d6082621b6b50c2604890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/hashicorp/consul/api/LICENSE %{buildroot}/usr/share/package-licenses/traefik/523489384296f403da31edf8edf6f9023d328517
cp %{_builddir}/traefik-vendor-2.4.5/github.com/hashicorp/errwrap/LICENSE %{buildroot}/usr/share/package-licenses/traefik/523489384296f403da31edf8edf6f9023d328517
cp %{_builddir}/traefik-vendor-2.4.5/github.com/hashicorp/go-cleanhttp/LICENSE %{buildroot}/usr/share/package-licenses/traefik/fa7c4d75bae3a641d1f9ab5df028175bfb8a69ca
cp %{_builddir}/traefik-vendor-2.4.5/github.com/hashicorp/go-immutable-radix/LICENSE %{buildroot}/usr/share/package-licenses/traefik/fa7c4d75bae3a641d1f9ab5df028175bfb8a69ca
cp %{_builddir}/traefik-vendor-2.4.5/github.com/hashicorp/go-multierror/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2ebe302ef4d8d257ac6f0a916285b51937a25641
cp %{_builddir}/traefik-vendor-2.4.5/github.com/hashicorp/go-retryablehttp/LICENSE %{buildroot}/usr/share/package-licenses/traefik/fa7c4d75bae3a641d1f9ab5df028175bfb8a69ca
cp %{_builddir}/traefik-vendor-2.4.5/github.com/hashicorp/go-rootcerts/LICENSE %{buildroot}/usr/share/package-licenses/traefik/fa7c4d75bae3a641d1f9ab5df028175bfb8a69ca
cp %{_builddir}/traefik-vendor-2.4.5/github.com/hashicorp/go-version/LICENSE %{buildroot}/usr/share/package-licenses/traefik/523489384296f403da31edf8edf6f9023d328517
cp %{_builddir}/traefik-vendor-2.4.5/github.com/hashicorp/golang-lru/LICENSE %{buildroot}/usr/share/package-licenses/traefik/ece3df1263c100f93c427face535a292723d38e7
cp %{_builddir}/traefik-vendor-2.4.5/github.com/hashicorp/serf/LICENSE %{buildroot}/usr/share/package-licenses/traefik/523489384296f403da31edf8edf6f9023d328517
cp %{_builddir}/traefik-vendor-2.4.5/github.com/huandu/xstrings/LICENSE %{buildroot}/usr/share/package-licenses/traefik/8758b52c623c08eff9cadbd0f0e1541085e9984d
cp %{_builddir}/traefik-vendor-2.4.5/github.com/iij/doapi/LICENSE.md %{buildroot}/usr/share/package-licenses/traefik/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/traefik-vendor-2.4.5/github.com/imdario/mergo/LICENSE %{buildroot}/usr/share/package-licenses/traefik/eecfc0c7e0930c6ba1ed0ff2d46a0a6fa0d16d6c
cp %{_builddir}/traefik-vendor-2.4.5/github.com/influxdata/influxdb1-client/LICENSE %{buildroot}/usr/share/package-licenses/traefik/bb2c730bc80365a987aefc7827f1b33e140d59ac
cp %{_builddir}/traefik-vendor-2.4.5/github.com/instana/go-sensor/LICENSE.md %{buildroot}/usr/share/package-licenses/traefik/28f944cf7422d772bde0076a979b809c3a6a7410
cp %{_builddir}/traefik-vendor-2.4.5/github.com/jmespath/go-jmespath/LICENSE %{buildroot}/usr/share/package-licenses/traefik/4052101a660a7d8343c13ada130123f75f1dd408
cp %{_builddir}/traefik-vendor-2.4.5/github.com/joeshaw/multierror/LICENSE %{buildroot}/usr/share/package-licenses/traefik/ed625d580ba609e156ca1f9b0df922e400c61bdb
cp %{_builddir}/traefik-vendor-2.4.5/github.com/jonboulle/clockwork/LICENSE %{buildroot}/usr/share/package-licenses/traefik/92a74693f02c8e78dd90b2014c52bc35a95bab86
cp %{_builddir}/traefik-vendor-2.4.5/github.com/json-iterator/go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/810612ee8c1872b7ee4dba34c090ebd8f7491aa1
cp %{_builddir}/traefik-vendor-2.4.5/github.com/kolo/xmlrpc/LICENSE %{buildroot}/usr/share/package-licenses/traefik/c5201c091577e830cbe46183cde62975fbc3d0d8
cp %{_builddir}/traefik-vendor-2.4.5/github.com/labbsr0x/bindman-dns-webhook/LICENSE %{buildroot}/usr/share/package-licenses/traefik/6314d6102ef75b5fea07493235815af82f3baf89
cp %{_builddir}/traefik-vendor-2.4.5/github.com/labbsr0x/goh/LICENSE %{buildroot}/usr/share/package-licenses/traefik/5079557d79df329b733886e73ac1a62d912210a3
cp %{_builddir}/traefik-vendor-2.4.5/github.com/libkermit/compose/LICENSE %{buildroot}/usr/share/package-licenses/traefik/e9f243316d2abc6e4d7e66994eef8caba131e14a
cp %{_builddir}/traefik-vendor-2.4.5/github.com/libkermit/docker-check/LICENSE %{buildroot}/usr/share/package-licenses/traefik/e9f243316d2abc6e4d7e66994eef8caba131e14a
cp %{_builddir}/traefik-vendor-2.4.5/github.com/libkermit/docker/LICENSE %{buildroot}/usr/share/package-licenses/traefik/e9f243316d2abc6e4d7e66994eef8caba131e14a
cp %{_builddir}/traefik-vendor-2.4.5/github.com/linode/linodego/LICENSE %{buildroot}/usr/share/package-licenses/traefik/0f81a041d5fd6400423f7d6bbfc52a96a1150b2c
cp %{_builddir}/traefik-vendor-2.4.5/github.com/liquidweb/liquidweb-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/traefik-vendor-2.4.5/github.com/looplab/fsm/LICENSE %{buildroot}/usr/share/package-licenses/traefik/172ca3bbafe312a1cf09cfff26953db2f425c28e
cp %{_builddir}/traefik-vendor-2.4.5/github.com/mailgun/minheap/LICENSE %{buildroot}/usr/share/package-licenses/traefik/c700a8b9312d24bdc57570f7d6a131cf63d89016
cp %{_builddir}/traefik-vendor-2.4.5/github.com/mailgun/multibuf/LICENSE %{buildroot}/usr/share/package-licenses/traefik/c700a8b9312d24bdc57570f7d6a131cf63d89016
cp %{_builddir}/traefik-vendor-2.4.5/github.com/mailgun/timetools/LICENSE %{buildroot}/usr/share/package-licenses/traefik/c700a8b9312d24bdc57570f7d6a131cf63d89016
cp %{_builddir}/traefik-vendor-2.4.5/github.com/mailgun/ttlmap/LICENSE %{buildroot}/usr/share/package-licenses/traefik/c700a8b9312d24bdc57570f7d6a131cf63d89016
cp %{_builddir}/traefik-vendor-2.4.5/github.com/mailru/easyjson/LICENSE %{buildroot}/usr/share/package-licenses/traefik/554fb441fbb1607579b7c9f8e9d7fab5d00e3a51
cp %{_builddir}/traefik-vendor-2.4.5/github.com/matttproud/golang_protobuf_extensions/LICENSE %{buildroot}/usr/share/package-licenses/traefik/92170cdc034b2ff819323ff670d3b7266c8bffcd
cp %{_builddir}/traefik-vendor-2.4.5/github.com/miekg/dns/LICENSE %{buildroot}/usr/share/package-licenses/traefik/33381fbc641abf311a0ebfedca0ce835f3cb933c
cp %{_builddir}/traefik-vendor-2.4.5/github.com/mitchellh/copystructure/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d676a57141ac47c27699fc8b03e1a2e59abb96ef
cp %{_builddir}/traefik-vendor-2.4.5/github.com/mitchellh/go-homedir/LICENSE %{buildroot}/usr/share/package-licenses/traefik/5ad2002bc8d2b22e2034867d159f71ba6258e18f
cp %{_builddir}/traefik-vendor-2.4.5/github.com/mitchellh/hashstructure/LICENSE %{buildroot}/usr/share/package-licenses/traefik/5e532746c55cbcc078e80cff9c6c532db022f7b2
cp %{_builddir}/traefik-vendor-2.4.5/github.com/mitchellh/mapstructure/LICENSE %{buildroot}/usr/share/package-licenses/traefik/5ad2002bc8d2b22e2034867d159f71ba6258e18f
cp %{_builddir}/traefik-vendor-2.4.5/github.com/mitchellh/reflectwalk/LICENSE %{buildroot}/usr/share/package-licenses/traefik/5ad2002bc8d2b22e2034867d159f71ba6258e18f
cp %{_builddir}/traefik-vendor-2.4.5/github.com/modern-go/concurrent/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/traefik-vendor-2.4.5/github.com/modern-go/reflect2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/traefik-vendor-2.4.5/github.com/morikuni/aec/LICENSE %{buildroot}/usr/share/package-licenses/traefik/3faf341fbc32621fe1ac089ae2ab7a23980fc189
cp %{_builddir}/traefik-vendor-2.4.5/github.com/namedotcom/go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/c67c0dacb6da6ba6867aa457729de0450ce22190
cp %{_builddir}/traefik-vendor-2.4.5/github.com/nrdcg/auroradns/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d22157abc0fc0b4ae96380c09528e23cf77290a9
cp %{_builddir}/traefik-vendor-2.4.5/github.com/nrdcg/desec/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d22157abc0fc0b4ae96380c09528e23cf77290a9
cp %{_builddir}/traefik-vendor-2.4.5/github.com/nrdcg/dnspod-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/5d15467bc1a0277da625481ed8f7d6ea3f0d6ff6
cp %{_builddir}/traefik-vendor-2.4.5/github.com/nrdcg/goinwx/LICENSE %{buildroot}/usr/share/package-licenses/traefik/14ffb7e9c70576ffbfdc66a148ccd0bce8585c74
cp %{_builddir}/traefik-vendor-2.4.5/github.com/nrdcg/namesilo/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d22157abc0fc0b4ae96380c09528e23cf77290a9
cp %{_builddir}/traefik-vendor-2.4.5/github.com/opencontainers/go-digest/LICENSE.code %{buildroot}/usr/share/package-licenses/traefik/76a37a42a06aa6e231383fb93d9161f074d5962b
cp %{_builddir}/traefik-vendor-2.4.5/github.com/opencontainers/go-digest/LICENSE.docs %{buildroot}/usr/share/package-licenses/traefik/979fd7d5c67073b265d96f584aac3de1c419b8e2
cp %{_builddir}/traefik-vendor-2.4.5/github.com/opencontainers/image-spec/LICENSE %{buildroot}/usr/share/package-licenses/traefik/298850a6cdb155f54cfa44641df70b36228ed031
cp %{_builddir}/traefik-vendor-2.4.5/github.com/opencontainers/runc/LICENSE %{buildroot}/usr/share/package-licenses/traefik/8ff574408142cd6bbb2a1b83302de24cb7b35e8b
cp %{_builddir}/traefik-vendor-2.4.5/github.com/opentracing-contrib/go-observer/LICENSE %{buildroot}/usr/share/package-licenses/traefik/ce3ced7dfc56b25f4c446ec1b4e3256bacd574cd
cp %{_builddir}/traefik-vendor-2.4.5/github.com/opentracing/basictracer-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/75b05723a69674cde02ec34aac00db38fbbabccd
cp %{_builddir}/traefik-vendor-2.4.5/github.com/opentracing/opentracing-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/9277f25d2ab38e908276aff21eb9ec917583277a
cp %{_builddir}/traefik-vendor-2.4.5/github.com/openzipkin-contrib/zipkin-go-opentracing/LICENSE %{buildroot}/usr/share/package-licenses/traefik/f34888e960100544c20c19701e3dadfac1af81bd
cp %{_builddir}/traefik-vendor-2.4.5/github.com/openzipkin/zipkin-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/f34888e960100544c20c19701e3dadfac1af81bd
cp %{_builddir}/traefik-vendor-2.4.5/github.com/oracle/oci-go-sdk/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/63c11346f8959f3c01249becbb680a9f1f8ed816
cp %{_builddir}/traefik-vendor-2.4.5/github.com/ovh/go-ovh/LICENSE %{buildroot}/usr/share/package-licenses/traefik/5f2398afa3ec984a62741885b5479a33e594d181
cp %{_builddir}/traefik-vendor-2.4.5/github.com/patrickmn/go-cache/LICENSE %{buildroot}/usr/share/package-licenses/traefik/4da388cb14535cb8d2beb61b160aab2a2043a8c0
cp %{_builddir}/traefik-vendor-2.4.5/github.com/philhofer/fwd/LICENSE.md %{buildroot}/usr/share/package-licenses/traefik/8721a7bceeac027c5c20d20dd5756f78bad3368c
cp %{_builddir}/traefik-vendor-2.4.5/github.com/pires/go-proxyproto/LICENSE %{buildroot}/usr/share/package-licenses/traefik/92170cdc034b2ff819323ff670d3b7266c8bffcd
cp %{_builddir}/traefik-vendor-2.4.5/github.com/pkg/errors/LICENSE %{buildroot}/usr/share/package-licenses/traefik/9c1bedc0d42f24c24a1bd266f3ce101a4b0579fc
cp %{_builddir}/traefik-vendor-2.4.5/github.com/pmezard/go-difflib/LICENSE %{buildroot}/usr/share/package-licenses/traefik/cd3e4d932cee20da681e6b3bee8139cb4f734034
cp %{_builddir}/traefik-vendor-2.4.5/github.com/pquerna/otp/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/prometheus/client_golang/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/traefik-vendor-2.4.5/github.com/prometheus/client_golang/NOTICE %{buildroot}/usr/share/package-licenses/traefik/fd6460234f122a19f21affb6d6885269340b9176
cp %{_builddir}/traefik-vendor-2.4.5/github.com/prometheus/client_model/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/traefik-vendor-2.4.5/github.com/prometheus/common/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/traefik-vendor-2.4.5/github.com/prometheus/procfs/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/traefik-vendor-2.4.5/github.com/rancher/go-rancher-metadata/LICENSE %{buildroot}/usr/share/package-licenses/traefik/598f87f072f66e2269dd6919292b2934dbb20492
cp %{_builddir}/traefik-vendor-2.4.5/github.com/sacloud/libsacloud/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/github.com/samuel/go-zookeeper/LICENSE %{buildroot}/usr/share/package-licenses/traefik/64cb196f8a0194cc5cfac1fda01a7f5fde7a82c5
cp %{_builddir}/traefik-vendor-2.4.5/github.com/santhosh-tekuri/jsonschema/LICENSE %{buildroot}/usr/share/package-licenses/traefik/6bd2ee0934b11c441fd0ef30c2d3530c639eb7f0
cp %{_builddir}/traefik-vendor-2.4.5/github.com/sirupsen/logrus/LICENSE %{buildroot}/usr/share/package-licenses/traefik/a1c7852c717fed2c9a0284ed112ea66013230da6
cp %{_builddir}/traefik-vendor-2.4.5/github.com/spf13/cast/LICENSE %{buildroot}/usr/share/package-licenses/traefik/feb9285b75d0c82a47d32e7d4dc84eb02db9ee34
cp %{_builddir}/traefik-vendor-2.4.5/github.com/spf13/pflag/LICENSE %{buildroot}/usr/share/package-licenses/traefik/b3c86ae465b21f7323059db335158b48187731c7
cp %{_builddir}/traefik-vendor-2.4.5/github.com/stretchr/objx/LICENSE %{buildroot}/usr/share/package-licenses/traefik/9d0e87d9ac5974470fc21c575854718e8b6516be
cp %{_builddir}/traefik-vendor-2.4.5/github.com/stretchr/testify/LICENSE %{buildroot}/usr/share/package-licenses/traefik/892204393ca075d09c8b1c1d880aba1ae0a2b805
cp %{_builddir}/traefik-vendor-2.4.5/github.com/stvp/go-udp-testing/LICENSE %{buildroot}/usr/share/package-licenses/traefik/6ce9c3ae364ebab944f93b98553bd0e8efe93671
cp %{_builddir}/traefik-vendor-2.4.5/github.com/tinylib/msgp/LICENSE %{buildroot}/usr/share/package-licenses/traefik/6ee3b1301fdafb4771b65d6ecc15ed27e9864107
cp %{_builddir}/traefik-vendor-2.4.5/github.com/traefik/gziphandler/LICENSE %{buildroot}/usr/share/package-licenses/traefik/ce9a12164352c2182a74f5ca6b245b139069706e
cp %{_builddir}/traefik-vendor-2.4.5/github.com/traefik/paerser/LICENSE %{buildroot}/usr/share/package-licenses/traefik/3b353f82008f9dd0c25ffe2d291438f137275517
cp %{_builddir}/traefik-vendor-2.4.5/github.com/traefik/yaegi/LICENSE %{buildroot}/usr/share/package-licenses/traefik/5a2e83a4a737b79bf2dfa69be43ac24c120f0721
cp %{_builddir}/traefik-vendor-2.4.5/github.com/transip/gotransip/v6/LICENSE %{buildroot}/usr/share/package-licenses/traefik/1e71af214ea76876d0651b967832c580fdf102ec
cp %{_builddir}/traefik-vendor-2.4.5/github.com/uber/jaeger-client-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/traefik-vendor-2.4.5/github.com/uber/jaeger-lib/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/traefik-vendor-2.4.5/github.com/unrolled/render/LICENSE %{buildroot}/usr/share/package-licenses/traefik/17fe614fec6ecf2f2b1236b45b5448af821064df
cp %{_builddir}/traefik-vendor-2.4.5/github.com/unrolled/secure/LICENSE %{buildroot}/usr/share/package-licenses/traefik/17fe614fec6ecf2f2b1236b45b5448af821064df
cp %{_builddir}/traefik-vendor-2.4.5/github.com/vdemeester/shakers/LICENSE %{buildroot}/usr/share/package-licenses/traefik/e9f243316d2abc6e4d7e66994eef8caba131e14a
cp %{_builddir}/traefik-vendor-2.4.5/github.com/vulcand/oxy/LICENSE %{buildroot}/usr/share/package-licenses/traefik/c700a8b9312d24bdc57570f7d6a131cf63d89016
cp %{_builddir}/traefik-vendor-2.4.5/github.com/vulcand/predicate/LICENSE %{buildroot}/usr/share/package-licenses/traefik/c700a8b9312d24bdc57570f7d6a131cf63d89016
cp %{_builddir}/traefik-vendor-2.4.5/github.com/vultr/govultr/v2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/c4cc270b39d817d780086c83a688f031a16ba4af
cp %{_builddir}/traefik-vendor-2.4.5/github.com/xeipuuv/gojsonpointer/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/traefik/b7173385030ef97bce57b5b4b78b48763c83aed3
cp %{_builddir}/traefik-vendor-2.4.5/github.com/xeipuuv/gojsonreference/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/traefik/b7173385030ef97bce57b5b4b78b48763c83aed3
cp %{_builddir}/traefik-vendor-2.4.5/github.com/xeipuuv/gojsonschema/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/traefik/b7173385030ef97bce57b5b4b78b48763c83aed3
cp %{_builddir}/traefik-vendor-2.4.5/go.elastic.co/apm/LICENSE %{buildroot}/usr/share/package-licenses/traefik/b9ebd19bd63e43cf6c778f3e4865c90c8a14bdb8
cp %{_builddir}/traefik-vendor-2.4.5/go.elastic.co/apm/NOTICE %{buildroot}/usr/share/package-licenses/traefik/418fe93a7f3b7b41dd75d0c2fee1b2c65e7827ef
cp %{_builddir}/traefik-vendor-2.4.5/go.elastic.co/apm/module/apmhttp/LICENSE %{buildroot}/usr/share/package-licenses/traefik/b9ebd19bd63e43cf6c778f3e4865c90c8a14bdb8
cp %{_builddir}/traefik-vendor-2.4.5/go.elastic.co/apm/module/apmot/LICENSE %{buildroot}/usr/share/package-licenses/traefik/b9ebd19bd63e43cf6c778f3e4865c90c8a14bdb8
cp %{_builddir}/traefik-vendor-2.4.5/go.elastic.co/fastjson/LICENSE %{buildroot}/usr/share/package-licenses/traefik/653e2ded525585c769ae8345c0f831d61724ad87
cp %{_builddir}/traefik-vendor-2.4.5/go.etcd.io/etcd/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/go.opencensus.io/LICENSE %{buildroot}/usr/share/package-licenses/traefik/1128f8f91104ba9ef98d37eea6523a888dcfa5de
cp %{_builddir}/traefik-vendor-2.4.5/go.uber.org/atomic/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/fa2149c34ba4570e3325d4e09aee1b7f32d76679
cp %{_builddir}/traefik-vendor-2.4.5/go.uber.org/ratelimit/LICENSE %{buildroot}/usr/share/package-licenses/traefik/f88ca5aafa7498421a7c8b4f099ee31f8fb82151
cp %{_builddir}/traefik-vendor-2.4.5/golang.org/x/crypto/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d6a5f1ecaedd723c325a2063375b3517e808a2b5
cp %{_builddir}/traefik-vendor-2.4.5/golang.org/x/lint/LICENSE %{buildroot}/usr/share/package-licenses/traefik/98bd4176f4779516009b9effebe10231c836470d
cp %{_builddir}/traefik-vendor-2.4.5/golang.org/x/mod/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d6a5f1ecaedd723c325a2063375b3517e808a2b5
cp %{_builddir}/traefik-vendor-2.4.5/golang.org/x/net/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d6a5f1ecaedd723c325a2063375b3517e808a2b5
cp %{_builddir}/traefik-vendor-2.4.5/golang.org/x/oauth2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d6a5f1ecaedd723c325a2063375b3517e808a2b5
cp %{_builddir}/traefik-vendor-2.4.5/golang.org/x/sync/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d6a5f1ecaedd723c325a2063375b3517e808a2b5
cp %{_builddir}/traefik-vendor-2.4.5/golang.org/x/sys/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d6a5f1ecaedd723c325a2063375b3517e808a2b5
cp %{_builddir}/traefik-vendor-2.4.5/golang.org/x/text/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d6a5f1ecaedd723c325a2063375b3517e808a2b5
cp %{_builddir}/traefik-vendor-2.4.5/golang.org/x/time/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d6a5f1ecaedd723c325a2063375b3517e808a2b5
cp %{_builddir}/traefik-vendor-2.4.5/golang.org/x/tools/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d6a5f1ecaedd723c325a2063375b3517e808a2b5
cp %{_builddir}/traefik-vendor-2.4.5/golang.org/x/xerrors/LICENSE %{buildroot}/usr/share/package-licenses/traefik/844fb1cc442e5f3d1800e47ae5d76d11a872b91c
cp %{_builddir}/traefik-vendor-2.4.5/google.golang.org/api/LICENSE %{buildroot}/usr/share/package-licenses/traefik/ab32a5c14ccc0a6d38e173568a5577493e3f6870
cp %{_builddir}/traefik-vendor-2.4.5/google.golang.org/api/internal/third_party/uritemplates/LICENSE %{buildroot}/usr/share/package-licenses/traefik/475b0ccf682da5e05e3aa1eb6146b30132ae717d
cp %{_builddir}/traefik-vendor-2.4.5/google.golang.org/appengine/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/google.golang.org/genproto/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/google.golang.org/grpc/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/google.golang.org/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/traefik/74850a25a5319bdddc0d998eb8926c18bada282b
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/DataDog/dd-trace-go.v1/LICENSE %{buildroot}/usr/share/package-licenses/traefik/d9f5bde6c9f694afc4225df48b391b115fe23f12
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/DataDog/dd-trace-go.v1/LICENSE-3rdparty.csv %{buildroot}/usr/share/package-licenses/traefik/45885a47419b7bcba46b7523d6e815152504899e
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/fsnotify.v1/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7b421b3d8f9fe9dc8158b5e6efed1c448605ba92
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/inf.v0/LICENSE %{buildroot}/usr/share/package-licenses/traefik/580c0a1f1386fe13bce395d23bdaf3b14ae2e20b
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/ini.v1/LICENSE %{buildroot}/usr/share/package-licenses/traefik/e4ef54f2c30670f950d5e196afa09c88d8ef0c8a
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/ns1/ns1-go.v2/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/65a866cd5b85aa43abff58ad48b4ae07aa919a50
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/redis.v5/LICENSE %{buildroot}/usr/share/package-licenses/traefik/a5774e9525ac2b335ce9b3a3300e65178b4ff41f
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/square/go-jose.v2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/square/go-jose.v2/json/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7f7a12bcfc16fab2522aa1a562fd3d2aee429d3b
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/yaml.v2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/92170cdc034b2ff819323ff670d3b7266c8bffcd
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/yaml.v2/LICENSE.libyaml %{buildroot}/usr/share/package-licenses/traefik/ad00ce7340d89dc13ccc59920ef75cb55af5b164
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/yaml.v2/NOTICE %{buildroot}/usr/share/package-licenses/traefik/9522d95b2b9b284285cc3fb6ecc445aa3ee5e785
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/yaml.v3/LICENSE %{buildroot}/usr/share/package-licenses/traefik/b74b3b31bc15ad5e94fc1947d682aa3d84132fce
cp %{_builddir}/traefik-vendor-2.4.5/gopkg.in/yaml.v3/NOTICE %{buildroot}/usr/share/package-licenses/traefik/9522d95b2b9b284285cc3fb6ecc445aa3ee5e785
cp %{_builddir}/traefik-vendor-2.4.5/howett.net/plist/LICENSE %{buildroot}/usr/share/package-licenses/traefik/7a8ca7d5340266b1ae785e22ec529d7138433680
cp %{_builddir}/traefik-vendor-2.4.5/k8s.io/api/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/k8s.io/apimachinery/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/k8s.io/client-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/k8s.io/code-generator/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/k8s.io/gengo/LICENSE %{buildroot}/usr/share/package-licenses/traefik/8d27fd734630787bf68266a7f4fb6b4c55cd6853
cp %{_builddir}/traefik-vendor-2.4.5/k8s.io/klog/v2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/172ca3bbafe312a1cf09cfff26953db2f425c28e
cp %{_builddir}/traefik-vendor-2.4.5/k8s.io/kube-openapi/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/k8s.io/utils/LICENSE %{buildroot}/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/traefik-vendor-2.4.5/mvdan.cc/xurls/v2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/626866343039d137644ba84e733379ceb8c14d5a
cp %{_builddir}/traefik-vendor-2.4.5/sigs.k8s.io/service-apis/LICENSE %{buildroot}/usr/share/package-licenses/traefik/1f3bfdaccd74f4cd2c02ab416277c4f39b48dea3
cp %{_builddir}/traefik-vendor-2.4.5/sigs.k8s.io/structured-merge-diff/v4/LICENSE %{buildroot}/usr/share/package-licenses/traefik/92170cdc034b2ff819323ff670d3b7266c8bffcd
cp %{_builddir}/traefik-vendor-2.4.5/sigs.k8s.io/yaml/LICENSE %{buildroot}/usr/share/package-licenses/traefik/271aeaf56ee621c5accfc2a9db0b10717e038eaf
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/traefik

%files data
%defattr(-,root,root,-)
/usr/share/traefik/traefik.sample.toml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/traefik/01e537267fca176b08cd25a4e6e6a7092ed3c734
/usr/share/package-licenses/traefik/020acfcf6d6bd6d701d19bd16f49d0bf18441779
/usr/share/package-licenses/traefik/04319952ed7b0f3b3a70ae4d5d9f954317b8f970
/usr/share/package-licenses/traefik/06b27345acae9303e13dde9974d2b2e318b05989
/usr/share/package-licenses/traefik/08021ae73f58f423dd6e7b525e81cf2520f7619e
/usr/share/package-licenses/traefik/0c84bd26de8694ce5b00eedec272769f22a5538c
/usr/share/package-licenses/traefik/0f81a041d5fd6400423f7d6bbfc52a96a1150b2c
/usr/share/package-licenses/traefik/101c182fa18fd56a09164278f17e4282264c5e9e
/usr/share/package-licenses/traefik/1128f8f91104ba9ef98d37eea6523a888dcfa5de
/usr/share/package-licenses/traefik/11a8fec351554e8f6c3f4dac5a1f4049dd467ba8
/usr/share/package-licenses/traefik/12e48afc2b1eb5db59385d6b9b207f462a0fb271
/usr/share/package-licenses/traefik/14ffb7e9c70576ffbfdc66a148ccd0bce8585c74
/usr/share/package-licenses/traefik/172ca3bbafe312a1cf09cfff26953db2f425c28e
/usr/share/package-licenses/traefik/17c7cd81bb03c410ed4fb4859c3caf55d16e8cab
/usr/share/package-licenses/traefik/17fe614fec6ecf2f2b1236b45b5448af821064df
/usr/share/package-licenses/traefik/19faac93bab978326d06e3b96bbf41d495ce2a51
/usr/share/package-licenses/traefik/1e71af214ea76876d0651b967832c580fdf102ec
/usr/share/package-licenses/traefik/1f3bfdaccd74f4cd2c02ab416277c4f39b48dea3
/usr/share/package-licenses/traefik/2028422a9ed73d6afc856a46f41ff4207f4aed8d
/usr/share/package-licenses/traefik/20b06a68cf65738d43afa04acce0126f341c77f8
/usr/share/package-licenses/traefik/21b9019f7aa793ffcba310799b9909430c426839
/usr/share/package-licenses/traefik/239eb7b8270d659c1316e04c7081921142226198
/usr/share/package-licenses/traefik/23d68de7aa2faedcbe131e4ff5b1fdd25af585dd
/usr/share/package-licenses/traefik/267ef34592bbf4b90c2aee662050e00de8aab9a6
/usr/share/package-licenses/traefik/271aeaf56ee621c5accfc2a9db0b10717e038eaf
/usr/share/package-licenses/traefik/28f944cf7422d772bde0076a979b809c3a6a7410
/usr/share/package-licenses/traefik/298850a6cdb155f54cfa44641df70b36228ed031
/usr/share/package-licenses/traefik/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/traefik/2bda142bd58fd76f408cf18fa997d8fab0278a22
/usr/share/package-licenses/traefik/2ebe302ef4d8d257ac6f0a916285b51937a25641
/usr/share/package-licenses/traefik/307711a68aa375a23d90191db6f720426cf88402
/usr/share/package-licenses/traefik/308c47a3ea356402d2d14241da9a9f64cf404008
/usr/share/package-licenses/traefik/3110e55750143a84918d7423febc9c83a55bc28c
/usr/share/package-licenses/traefik/33381fbc641abf311a0ebfedca0ce835f3cb933c
/usr/share/package-licenses/traefik/33cd8e150548e595fbe201c6ca9df582976e71db
/usr/share/package-licenses/traefik/34554dbd133157d01181d9849768152d3c68149e
/usr/share/package-licenses/traefik/34b266cae5bba7e3b33a080c3d328f9aa598e806
/usr/share/package-licenses/traefik/376caa2cd54c4196280157d071524614350e7ce8
/usr/share/package-licenses/traefik/3ad128f30b382b49f591245750c269076248de2b
/usr/share/package-licenses/traefik/3b353f82008f9dd0c25ffe2d291438f137275517
/usr/share/package-licenses/traefik/3faf341fbc32621fe1ac089ae2ab7a23980fc189
/usr/share/package-licenses/traefik/4052101a660a7d8343c13ada130123f75f1dd408
/usr/share/package-licenses/traefik/417483c9ccd2847921fd8605edf02b5a243b4761
/usr/share/package-licenses/traefik/418fe93a7f3b7b41dd75d0c2fee1b2c65e7827ef
/usr/share/package-licenses/traefik/4278180522ac398eca5a90de73b4f29a4e9aef82
/usr/share/package-licenses/traefik/45885a47419b7bcba46b7523d6e815152504899e
/usr/share/package-licenses/traefik/475b0ccf682da5e05e3aa1eb6146b30132ae717d
/usr/share/package-licenses/traefik/4da388cb14535cb8d2beb61b160aab2a2043a8c0
/usr/share/package-licenses/traefik/4e969f5760ada4247efca2e282cd450b5df37f9a
/usr/share/package-licenses/traefik/5079557d79df329b733886e73ac1a62d912210a3
/usr/share/package-licenses/traefik/523489384296f403da31edf8edf6f9023d328517
/usr/share/package-licenses/traefik/535e3badf5b532d842627b504976fbb93bc2d8b8
/usr/share/package-licenses/traefik/5473ed979e3291e2de03eb43700bf4953b1bb7ae
/usr/share/package-licenses/traefik/5476f2f91673ef040f1956907e7f45e72d5e11ee
/usr/share/package-licenses/traefik/554fb441fbb1607579b7c9f8e9d7fab5d00e3a51
/usr/share/package-licenses/traefik/555e9ac61d94352b3c2935e77b51fc6dc31d4822
/usr/share/package-licenses/traefik/56b820712432e458f05f883566ca8cd85dcdaad5
/usr/share/package-licenses/traefik/580c0a1f1386fe13bce395d23bdaf3b14ae2e20b
/usr/share/package-licenses/traefik/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/traefik/5a2e83a4a737b79bf2dfa69be43ac24c120f0721
/usr/share/package-licenses/traefik/5a7d7df655ba40478fae80a6abafc6afc36f9b6a
/usr/share/package-licenses/traefik/5ad2002bc8d2b22e2034867d159f71ba6258e18f
/usr/share/package-licenses/traefik/5d06409981dfdb6c13963148f9a18c5c3eaac4fe
/usr/share/package-licenses/traefik/5d15467bc1a0277da625481ed8f7d6ea3f0d6ff6
/usr/share/package-licenses/traefik/5d833085cd09e0a70fe9071b1f2edf6d31b91d45
/usr/share/package-licenses/traefik/5e532746c55cbcc078e80cff9c6c532db022f7b2
/usr/share/package-licenses/traefik/5f2398afa3ec984a62741885b5479a33e594d181
/usr/share/package-licenses/traefik/626866343039d137644ba84e733379ceb8c14d5a
/usr/share/package-licenses/traefik/6314d6102ef75b5fea07493235815af82f3baf89
/usr/share/package-licenses/traefik/63c11346f8959f3c01249becbb680a9f1f8ed816
/usr/share/package-licenses/traefik/64cb196f8a0194cc5cfac1fda01a7f5fde7a82c5
/usr/share/package-licenses/traefik/653e2ded525585c769ae8345c0f831d61724ad87
/usr/share/package-licenses/traefik/65a866cd5b85aa43abff58ad48b4ae07aa919a50
/usr/share/package-licenses/traefik/6bd2ee0934b11c441fd0ef30c2d3530c639eb7f0
/usr/share/package-licenses/traefik/6ce9c3ae364ebab944f93b98553bd0e8efe93671
/usr/share/package-licenses/traefik/6ee3b1301fdafb4771b65d6ecc15ed27e9864107
/usr/share/package-licenses/traefik/702efc433d30e282422d6082621b6b50c2604890
/usr/share/package-licenses/traefik/7080652cc78cd9855d39e324529a3b5f3745dcd6
/usr/share/package-licenses/traefik/7280d51677a5550c328b89f3db1f5e87427f2533
/usr/share/package-licenses/traefik/74850a25a5319bdddc0d998eb8926c18bada282b
/usr/share/package-licenses/traefik/75b05723a69674cde02ec34aac00db38fbbabccd
/usr/share/package-licenses/traefik/76a37a42a06aa6e231383fb93d9161f074d5962b
/usr/share/package-licenses/traefik/78d6de13df5ab04962a5301b2fa08e6da55f1aba
/usr/share/package-licenses/traefik/7a8ca7d5340266b1ae785e22ec529d7138433680
/usr/share/package-licenses/traefik/7b421b3d8f9fe9dc8158b5e6efed1c448605ba92
/usr/share/package-licenses/traefik/7be82c1a81e7197640a88df91dc82d64b77c7acd
/usr/share/package-licenses/traefik/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/traefik/7f7a12bcfc16fab2522aa1a562fd3d2aee429d3b
/usr/share/package-licenses/traefik/810612ee8c1872b7ee4dba34c090ebd8f7491aa1
/usr/share/package-licenses/traefik/818cd8d3934fc2af85e81c1f39c51ef7f661c139
/usr/share/package-licenses/traefik/836ef1b46953afdb78ce3929bc6831ca83620b65
/usr/share/package-licenses/traefik/844fb1cc442e5f3d1800e47ae5d76d11a872b91c
/usr/share/package-licenses/traefik/861181924d993ee58a17a2c3c3a3faecf895849c
/usr/share/package-licenses/traefik/8721a7bceeac027c5c20d20dd5756f78bad3368c
/usr/share/package-licenses/traefik/8758b52c623c08eff9cadbd0f0e1541085e9984d
/usr/share/package-licenses/traefik/878e7d86573d6c8ff65d2eaab294734b3f4d3d81
/usr/share/package-licenses/traefik/892204393ca075d09c8b1c1d880aba1ae0a2b805
/usr/share/package-licenses/traefik/8ac28139bb1d105323e9ec990b68488edcf427fd
/usr/share/package-licenses/traefik/8d27fd734630787bf68266a7f4fb6b4c55cd6853
/usr/share/package-licenses/traefik/8ff574408142cd6bbb2a1b83302de24cb7b35e8b
/usr/share/package-licenses/traefik/904db295d780f20aeb75042f236708b28edcdfc1
/usr/share/package-licenses/traefik/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/traefik/9277f25d2ab38e908276aff21eb9ec917583277a
/usr/share/package-licenses/traefik/92a74693f02c8e78dd90b2014c52bc35a95bab86
/usr/share/package-licenses/traefik/9522d95b2b9b284285cc3fb6ecc445aa3ee5e785
/usr/share/package-licenses/traefik/96e730c77952892784bebe06fd42b297b67ea06e
/usr/share/package-licenses/traefik/979fd7d5c67073b265d96f584aac3de1c419b8e2
/usr/share/package-licenses/traefik/98bd4176f4779516009b9effebe10231c836470d
/usr/share/package-licenses/traefik/9a42583034b13e145f6c077b013f1f27da13c1d9
/usr/share/package-licenses/traefik/9c1bedc0d42f24c24a1bd266f3ce101a4b0579fc
/usr/share/package-licenses/traefik/9d0e87d9ac5974470fc21c575854718e8b6516be
/usr/share/package-licenses/traefik/a1b4279f3ae16b42693f03c8c610df15a32f02da
/usr/share/package-licenses/traefik/a1c7852c717fed2c9a0284ed112ea66013230da6
/usr/share/package-licenses/traefik/a5774e9525ac2b335ce9b3a3300e65178b4ff41f
/usr/share/package-licenses/traefik/a8993f4a51771a0333dbbc5b1c4395a2ccaa4d9f
/usr/share/package-licenses/traefik/aa9b240f558caed367795f667629ccbca28f20b2
/usr/share/package-licenses/traefik/ab32a5c14ccc0a6d38e173568a5577493e3f6870
/usr/share/package-licenses/traefik/ad00ce7340d89dc13ccc59920ef75cb55af5b164
/usr/share/package-licenses/traefik/aee2763a63c10c110c21f1942cf8e3187009148c
/usr/share/package-licenses/traefik/b132e03c6b6bd85fbc2394f808acae8f5d0ebaf0
/usr/share/package-licenses/traefik/b2e4520feb0f9b51ad373256b94c3faf4c1e6871
/usr/share/package-licenses/traefik/b3c86ae465b21f7323059db335158b48187731c7
/usr/share/package-licenses/traefik/b4b35a8138ee83256aca752d3813d3d0757d8380
/usr/share/package-licenses/traefik/b610f9367f8cbc6221c6c9319caf09ab07786268
/usr/share/package-licenses/traefik/b7173385030ef97bce57b5b4b78b48763c83aed3
/usr/share/package-licenses/traefik/b74b3b31bc15ad5e94fc1947d682aa3d84132fce
/usr/share/package-licenses/traefik/b9ebd19bd63e43cf6c778f3e4865c90c8a14bdb8
/usr/share/package-licenses/traefik/bb2c730bc80365a987aefc7827f1b33e140d59ac
/usr/share/package-licenses/traefik/c3449b45ed5b8824cf5973495f72bf4b2370f46f
/usr/share/package-licenses/traefik/c4cc270b39d817d780086c83a688f031a16ba4af
/usr/share/package-licenses/traefik/c5201c091577e830cbe46183cde62975fbc3d0d8
/usr/share/package-licenses/traefik/c67c0dacb6da6ba6867aa457729de0450ce22190
/usr/share/package-licenses/traefik/c6ad24467b71e3c84eb2d73dffb7fd168e203c4a
/usr/share/package-licenses/traefik/c700a8b9312d24bdc57570f7d6a131cf63d89016
/usr/share/package-licenses/traefik/cd25196630fe891662ad77810f0f6dee5bc85ddc
/usr/share/package-licenses/traefik/cd3e4d932cee20da681e6b3bee8139cb4f734034
/usr/share/package-licenses/traefik/ce3ced7dfc56b25f4c446ec1b4e3256bacd574cd
/usr/share/package-licenses/traefik/ce9a12164352c2182a74f5ca6b245b139069706e
/usr/share/package-licenses/traefik/d22157abc0fc0b4ae96380c09528e23cf77290a9
/usr/share/package-licenses/traefik/d2f340a01dd48b589a70f627cf7058c585a315e4
/usr/share/package-licenses/traefik/d3b7a70b03b43d4e7205d178100581923a0baad2
/usr/share/package-licenses/traefik/d3d30f733d36ea721eb89e9c37f899f729a0ea5e
/usr/share/package-licenses/traefik/d676a57141ac47c27699fc8b03e1a2e59abb96ef
/usr/share/package-licenses/traefik/d6a5f1ecaedd723c325a2063375b3517e808a2b5
/usr/share/package-licenses/traefik/d80a2259c41a1be1d07366c4df5d2edf3afede27
/usr/share/package-licenses/traefik/d9f5bde6c9f694afc4225df48b391b115fe23f12
/usr/share/package-licenses/traefik/de6aabbb551ff752e690d7a1136a5b5228f130cb
/usr/share/package-licenses/traefik/e0bb5df1969ef7b428077d4a2441d81678ec4846
/usr/share/package-licenses/traefik/e4ef54f2c30670f950d5e196afa09c88d8ef0c8a
/usr/share/package-licenses/traefik/e9f243316d2abc6e4d7e66994eef8caba131e14a
/usr/share/package-licenses/traefik/ec2d07fe9c52f1a0cb319e200c30d4e40045ad37
/usr/share/package-licenses/traefik/ece3df1263c100f93c427face535a292723d38e7
/usr/share/package-licenses/traefik/ed625d580ba609e156ca1f9b0df922e400c61bdb
/usr/share/package-licenses/traefik/eecfc0c7e0930c6ba1ed0ff2d46a0a6fa0d16d6c
/usr/share/package-licenses/traefik/f0b513a735cc88cc1f37c5ee0caec2a9e154bd86
/usr/share/package-licenses/traefik/f34888e960100544c20c19701e3dadfac1af81bd
/usr/share/package-licenses/traefik/f3eab54cb1736b419ef75b8c44bea2b17614bd31
/usr/share/package-licenses/traefik/f88ca5aafa7498421a7c8b4f099ee31f8fb82151
/usr/share/package-licenses/traefik/f9cab757896ef6b3570e62b2df7fb63ab1a34b80
/usr/share/package-licenses/traefik/fa2149c34ba4570e3325d4e09aee1b7f32d76679
/usr/share/package-licenses/traefik/fa7c4d75bae3a641d1f9ab5df028175bfb8a69ca
/usr/share/package-licenses/traefik/fb1bf49ddf574b8e6d1863539b1a08ec3b66d05e
/usr/share/package-licenses/traefik/fd6460234f122a19f21affb6d6885269340b9176
/usr/share/package-licenses/traefik/feb9285b75d0c82a47d32e7d4dc84eb02db9ee34

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/traefik.service
