#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : traefik
Version  : 2.0.1
Release  : 2
URL      : https://github.com/containous/traefik/archive/v2.0.1.tar.gz
Source0  : https://github.com/containous/traefik/archive/v2.0.1.tar.gz
Source1  : http://localhost/cgit/projects/traefik-vendor/snapshot/traefik-vendor-2.0.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause CC-BY-SA-4.0 ISC MIT MPL-2.0 MPL-2.0-no-copyleft-exception
Requires: traefik-bin = %{version}-%{release}
Requires: traefik-data = %{version}-%{release}
Requires: traefik-license = %{version}-%{release}
Requires: traefik-services = %{version}-%{release}
BuildRequires : buildreq-golang
BuildRequires : go-github.com-BurntSushi-toml
BuildRequires : go-github.com-spf13-pflag
Patch1: 0001-Switch-to-just-building-the-traefik-binary.patch

%description
Go package for parsing (and, eventually, generating)
log lines in the logfmt style.

%package bin
Summary: bin components for the traefik package.
Group: Binaries
Requires: traefik-data = %{version}-%{release}
Requires: traefik-license = %{version}-%{release}
Requires: traefik-services = %{version}-%{release}

%description bin
bin components for the traefik package.


%package data
Summary: data components for the traefik package.
Group: Data

%description data
data components for the traefik package.


%package license
Summary: license components for the traefik package.
Group: Default

%description license
license components for the traefik package.


%package services
Summary: services components for the traefik package.
Group: Systemd services

%description services
services components for the traefik package.


%prep
%setup -q -n traefik-2.0.1
cd ..
%setup -q -T -D -n traefik-2.0.1 -b 1
mkdir -p vendor
cp -r %{_topdir}/BUILD/traefik-vendor-2.0.1/* %{_topdir}/BUILD/traefik-2.0.1/vendor
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570136152
export GCC_IGNORE_WERROR=1
export GOPROXY=file:///usr/share/goproxy
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1570136152
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/traefik
cp LICENSE.md %{buildroot}/usr/share/package-licenses/traefik/LICENSE.md
cp docs/content/assets/js/hljs/LICENSE %{buildroot}/usr/share/package-licenses/traefik/docs_content_assets_js_hljs_LICENSE
cp vendor/cloud.google.com/go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_cloud.google.com_go_LICENSE
cp vendor/contrib.go.opencensus.io/exporter/ocagent/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_contrib.go.opencensus.io_exporter_ocagent_LICENSE
cp vendor/github.com/Azure/azure-sdk-for-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Azure_azure-sdk-for-go_LICENSE
cp vendor/github.com/Azure/go-ansiterm/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-ansiterm_LICENSE
cp vendor/github.com/Azure/go-autorest/autorest/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_LICENSE
cp vendor/github.com/Azure/go-autorest/autorest/adal/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_adal_LICENSE
cp vendor/github.com/Azure/go-autorest/autorest/azure/auth/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_azure_auth_LICENSE
cp vendor/github.com/Azure/go-autorest/autorest/azure/cli/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_azure_cli_LICENSE
cp vendor/github.com/Azure/go-autorest/autorest/date/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_date_LICENSE
cp vendor/github.com/Azure/go-autorest/autorest/to/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_to_LICENSE
cp vendor/github.com/Azure/go-autorest/autorest/validation/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_validation_LICENSE
cp vendor/github.com/Azure/go-autorest/logger/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_logger_LICENSE
cp vendor/github.com/Azure/go-autorest/tracing/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_tracing_LICENSE
cp vendor/github.com/BurntSushi/toml/COPYING %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_BurntSushi_toml_COPYING
cp vendor/github.com/ExpediaDotCom/haystack-client-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_ExpediaDotCom_haystack-client-go_LICENSE
cp vendor/github.com/Masterminds/goutils/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Masterminds_goutils_LICENSE.txt
cp vendor/github.com/Masterminds/semver/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Masterminds_semver_LICENSE.txt
cp vendor/github.com/Masterminds/sprig/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Masterminds_sprig_LICENSE.txt
cp vendor/github.com/Microsoft/go-winio/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Microsoft_go-winio_LICENSE
cp vendor/github.com/Microsoft/hcsshim/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_Microsoft_hcsshim_LICENSE
cp vendor/github.com/NYTimes/gziphandler/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_NYTimes_gziphandler_LICENSE
cp vendor/github.com/OpenDNS/vegadns2client/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_OpenDNS_vegadns2client_LICENSE
cp vendor/github.com/VividCortex/gohistogram/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_VividCortex_gohistogram_LICENSE
cp vendor/github.com/abbot/go-http-auth/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_abbot_go-http-auth_LICENSE
cp vendor/github.com/abronan/valkeyrie/LICENSE.code %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_abronan_valkeyrie_LICENSE.code
cp vendor/github.com/abronan/valkeyrie/LICENSE.docs %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_abronan_valkeyrie_LICENSE.docs
cp vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_akamai_AkamaiOPEN-edgegrid-golang_LICENSE
cp vendor/github.com/aliyun/alibaba-cloud-sdk-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_aliyun_alibaba-cloud-sdk-go_LICENSE
cp vendor/github.com/aws/aws-sdk-go/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_aws_aws-sdk-go_LICENSE.txt
cp vendor/github.com/beorn7/perks/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_beorn7_perks_LICENSE
cp vendor/github.com/c0va23/go-proxyprotocol/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_c0va23_go-proxyprotocol_LICENSE
cp vendor/github.com/cenkalti/backoff/v3/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_cenkalti_backoff_v3_LICENSE
cp vendor/github.com/census-instrumentation/opencensus-proto/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_census-instrumentation_opencensus-proto_LICENSE
cp vendor/github.com/cloudflare/cloudflare-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_cloudflare_cloudflare-go_LICENSE
cp vendor/github.com/codahale/hdrhistogram/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_codahale_hdrhistogram_LICENSE
cp vendor/github.com/containerd/continuity/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_containerd_continuity_LICENSE
cp vendor/github.com/containous/alice/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_containous_alice_LICENSE
cp vendor/github.com/coreos/go-systemd/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_coreos_go-systemd_LICENSE
cp vendor/github.com/cpu/goacmedns/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_cpu_goacmedns_LICENSE
cp vendor/github.com/davecgh/go-spew/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_davecgh_go-spew_LICENSE
cp vendor/github.com/decker502/dnspod-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_decker502_dnspod-go_LICENSE
cp vendor/github.com/dgrijalva/jwt-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_dgrijalva_jwt-go_LICENSE
cp vendor/github.com/dimchansky/utfbom/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_dimchansky_utfbom_LICENSE
cp vendor/github.com/dnsimple/dnsimple-go/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_dnsimple_dnsimple-go_LICENSE.txt
cp vendor/github.com/docker/cli/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_docker_cli_LICENSE
cp vendor/github.com/docker/cli/NOTICE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_docker_cli_NOTICE
cp vendor/github.com/docker/distribution/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_docker_distribution_LICENSE
cp vendor/github.com/docker/docker-credential-helpers/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_docker_docker-credential-helpers_LICENSE
cp vendor/github.com/docker/docker/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_docker_docker_LICENSE
cp vendor/github.com/docker/docker/NOTICE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_docker_docker_NOTICE
cp vendor/github.com/docker/docker/pkg/symlink/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_docker_docker_pkg_symlink_LICENSE.APACHE
cp vendor/github.com/docker/docker/pkg/symlink/LICENSE.BSD %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_docker_docker_pkg_symlink_LICENSE.BSD
cp vendor/github.com/docker/go-connections/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_docker_go-connections_LICENSE
cp vendor/github.com/docker/go-metrics/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_docker_go-metrics_LICENSE
cp vendor/github.com/docker/go-metrics/LICENSE.docs %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_docker_go-metrics_LICENSE.docs
cp vendor/github.com/docker/go-units/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_docker_go-units_LICENSE
cp vendor/github.com/docker/libcompose/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_docker_libcompose_LICENSE
cp vendor/github.com/eapache/channels/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_eapache_channels_LICENSE
cp vendor/github.com/eapache/queue/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_eapache_queue_LICENSE
cp vendor/github.com/elazarl/go-bindata-assetfs/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_elazarl_go-bindata-assetfs_LICENSE
cp vendor/github.com/evanphx/json-patch/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_evanphx_json-patch_LICENSE
cp vendor/github.com/exoscale/egoscale/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_exoscale_egoscale_LICENSE
cp vendor/github.com/fatih/structs/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_fatih_structs_LICENSE
cp vendor/github.com/felixge/httpsnoop/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_felixge_httpsnoop_LICENSE.txt
cp vendor/github.com/flynn/go-shlex/COPYING %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_flynn_go-shlex_COPYING
cp vendor/github.com/gambol99/go-marathon/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_gambol99_go-marathon_LICENSE
cp vendor/github.com/go-acme/lego/v3/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_go-acme_lego_v3_LICENSE
cp vendor/github.com/go-check/check/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_go-check_check_LICENSE
cp vendor/github.com/go-errors/errors/LICENSE.MIT %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_go-errors_errors_LICENSE.MIT
cp vendor/github.com/go-ini/ini/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_go-ini_ini_LICENSE
cp vendor/github.com/go-kit/kit/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_go-kit_kit_LICENSE
cp vendor/github.com/go-logfmt/logfmt/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_go-logfmt_logfmt_LICENSE
cp vendor/github.com/gofrs/uuid/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_gofrs_uuid_LICENSE
cp vendor/github.com/gogo/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_gogo_protobuf_LICENSE
cp vendor/github.com/golang/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_golang_protobuf_LICENSE
cp vendor/github.com/google/go-cmp/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_google_go-cmp_LICENSE
cp vendor/github.com/google/go-github/v28/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_google_go-github_v28_LICENSE
cp vendor/github.com/google/go-querystring/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_google_go-querystring_LICENSE
cp vendor/github.com/google/gofuzz/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_google_gofuzz_LICENSE
cp vendor/github.com/google/uuid/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_google_uuid_LICENSE
cp vendor/github.com/googleapis/gax-go/v2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_googleapis_gax-go_v2_LICENSE
cp vendor/github.com/googleapis/gnostic/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_googleapis_gnostic_LICENSE
cp vendor/github.com/gophercloud/gophercloud/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_gophercloud_gophercloud_LICENSE
cp vendor/github.com/gorilla/context/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_gorilla_context_LICENSE
cp vendor/github.com/gorilla/mux/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_gorilla_mux_LICENSE
cp vendor/github.com/gorilla/websocket/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_gorilla_websocket_LICENSE
cp vendor/github.com/gravitational/trace/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_gravitational_trace_LICENSE
cp vendor/github.com/grpc-ecosystem/grpc-gateway/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_grpc-ecosystem_grpc-gateway_LICENSE.txt
cp vendor/github.com/hashicorp/go-version/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_hashicorp_go-version_LICENSE
cp vendor/github.com/hashicorp/golang-lru/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_hashicorp_golang-lru_LICENSE
cp vendor/github.com/huandu/xstrings/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_huandu_xstrings_LICENSE
cp vendor/github.com/iij/doapi/LICENSE.md %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_iij_doapi_LICENSE.md
cp vendor/github.com/imdario/mergo/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_imdario_mergo_LICENSE
cp vendor/github.com/influxdata/influxdb1-client/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_influxdata_influxdb1-client_LICENSE
cp vendor/github.com/instana/go-sensor/LICENSE.md %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_instana_go-sensor_LICENSE.md
cp vendor/github.com/jmespath/go-jmespath/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_jmespath_go-jmespath_LICENSE
cp vendor/github.com/jonboulle/clockwork/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_jonboulle_clockwork_LICENSE
cp vendor/github.com/json-iterator/go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_json-iterator_go_LICENSE
cp vendor/github.com/kolo/xmlrpc/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_kolo_xmlrpc_LICENSE
cp vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_konsorten_go-windows-terminal-sequences_LICENSE
cp vendor/github.com/labbsr0x/bindman-dns-webhook/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_labbsr0x_bindman-dns-webhook_LICENSE
cp vendor/github.com/labbsr0x/goh/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_labbsr0x_goh_LICENSE
cp vendor/github.com/libkermit/compose/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_libkermit_compose_LICENSE
cp vendor/github.com/libkermit/docker-check/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_libkermit_docker-check_LICENSE
cp vendor/github.com/libkermit/docker/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_libkermit_docker_LICENSE
cp vendor/github.com/linode/linodego/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_linode_linodego_LICENSE
cp vendor/github.com/looplab/fsm/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_looplab_fsm_LICENSE
cp vendor/github.com/mailgun/minheap/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_mailgun_minheap_LICENSE
cp vendor/github.com/mailgun/multibuf/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_mailgun_multibuf_LICENSE
cp vendor/github.com/mailgun/timetools/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_mailgun_timetools_LICENSE
cp vendor/github.com/mailgun/ttlmap/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_mailgun_ttlmap_LICENSE
cp vendor/github.com/matttproud/golang_protobuf_extensions/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_matttproud_golang_protobuf_extensions_LICENSE
cp vendor/github.com/miekg/dns/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_miekg_dns_LICENSE
cp vendor/github.com/mitchellh/copystructure/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_mitchellh_copystructure_LICENSE
cp vendor/github.com/mitchellh/go-homedir/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_mitchellh_go-homedir_LICENSE
cp vendor/github.com/mitchellh/hashstructure/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_mitchellh_hashstructure_LICENSE
cp vendor/github.com/mitchellh/mapstructure/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_mitchellh_mapstructure_LICENSE
cp vendor/github.com/mitchellh/reflectwalk/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_mitchellh_reflectwalk_LICENSE
cp vendor/github.com/modern-go/concurrent/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_modern-go_concurrent_LICENSE
cp vendor/github.com/modern-go/reflect2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_modern-go_reflect2_LICENSE
cp vendor/github.com/morikuni/aec/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_morikuni_aec_LICENSE
cp vendor/github.com/namedotcom/go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_namedotcom_go_LICENSE
cp vendor/github.com/nrdcg/auroradns/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_nrdcg_auroradns_LICENSE
cp vendor/github.com/nrdcg/goinwx/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_nrdcg_goinwx_LICENSE
cp vendor/github.com/nrdcg/namesilo/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_nrdcg_namesilo_LICENSE
cp vendor/github.com/opencontainers/go-digest/LICENSE.code %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_opencontainers_go-digest_LICENSE.code
cp vendor/github.com/opencontainers/go-digest/LICENSE.docs %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_opencontainers_go-digest_LICENSE.docs
cp vendor/github.com/opencontainers/image-spec/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_opencontainers_image-spec_LICENSE
cp vendor/github.com/opencontainers/runc/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_opencontainers_runc_LICENSE
cp vendor/github.com/opentracing-contrib/go-observer/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_opentracing-contrib_go-observer_LICENSE
cp vendor/github.com/opentracing/basictracer-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_opentracing_basictracer-go_LICENSE
cp vendor/github.com/opentracing/opentracing-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_opentracing_opentracing-go_LICENSE
cp vendor/github.com/openzipkin-contrib/zipkin-go-opentracing/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_openzipkin-contrib_zipkin-go-opentracing_LICENSE
cp vendor/github.com/openzipkin/zipkin-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_openzipkin_zipkin-go_LICENSE
cp vendor/github.com/oracle/oci-go-sdk/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_oracle_oci-go-sdk_LICENSE.txt
cp vendor/github.com/ovh/go-ovh/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_ovh_go-ovh_LICENSE
cp vendor/github.com/patrickmn/go-cache/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_patrickmn_go-cache_LICENSE
cp vendor/github.com/philhofer/fwd/LICENSE.md %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_philhofer_fwd_LICENSE.md
cp vendor/github.com/pkg/errors/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_pkg_errors_LICENSE
cp vendor/github.com/pmezard/go-difflib/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_pmezard_go-difflib_LICENSE
cp vendor/github.com/prometheus/client_golang/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_prometheus_client_golang_LICENSE
cp vendor/github.com/prometheus/client_golang/NOTICE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_prometheus_client_golang_NOTICE
cp vendor/github.com/prometheus/client_model/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_prometheus_client_model_LICENSE
cp vendor/github.com/prometheus/common/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_prometheus_common_LICENSE
cp vendor/github.com/prometheus/procfs/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_prometheus_procfs_LICENSE
cp vendor/github.com/sacloud/libsacloud/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_sacloud_libsacloud_LICENSE.txt
cp vendor/github.com/sirupsen/logrus/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_sirupsen_logrus_LICENSE
cp vendor/github.com/spf13/pflag/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_spf13_pflag_LICENSE
cp vendor/github.com/stretchr/objx/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_stretchr_objx_LICENSE
cp vendor/github.com/stretchr/testify/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_stretchr_testify_LICENSE
cp vendor/github.com/stvp/go-udp-testing/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_stvp_go-udp-testing_LICENSE
cp vendor/github.com/timewasted/linode/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_timewasted_linode_LICENSE
cp vendor/github.com/tinylib/msgp/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_tinylib_msgp_LICENSE
cp vendor/github.com/transip/gotransip/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_transip_gotransip_LICENSE
cp vendor/github.com/uber/jaeger-client-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_uber_jaeger-client-go_LICENSE
cp vendor/github.com/uber/jaeger-lib/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_uber_jaeger-lib_LICENSE
cp vendor/github.com/unrolled/render/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_unrolled_render_LICENSE
cp vendor/github.com/unrolled/secure/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_unrolled_secure_LICENSE
cp vendor/github.com/vdemeester/shakers/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_vdemeester_shakers_LICENSE
cp vendor/github.com/vulcand/oxy/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_vulcand_oxy_LICENSE
cp vendor/github.com/vulcand/predicate/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_vulcand_predicate_LICENSE
cp vendor/github.com/vultr/govultr/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_vultr_govultr_LICENSE
cp vendor/github.com/xeipuuv/gojsonpointer/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_xeipuuv_gojsonpointer_LICENSE-APACHE-2.0.txt
cp vendor/github.com/xeipuuv/gojsonreference/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_xeipuuv_gojsonreference_LICENSE-APACHE-2.0.txt
cp vendor/github.com/xeipuuv/gojsonschema/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/traefik/vendor_github.com_xeipuuv_gojsonschema_LICENSE-APACHE-2.0.txt
cp vendor/go.opencensus.io/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_go.opencensus.io_LICENSE
cp vendor/go.uber.org/ratelimit/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_go.uber.org_ratelimit_LICENSE
cp vendor/golang.org/x/crypto/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_golang.org_x_crypto_LICENSE
cp vendor/golang.org/x/net/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_golang.org_x_net_LICENSE
cp vendor/golang.org/x/oauth2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_golang.org_x_oauth2_LICENSE
cp vendor/golang.org/x/sync/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_golang.org_x_sync_LICENSE
cp vendor/golang.org/x/sys/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_golang.org_x_sys_LICENSE
cp vendor/golang.org/x/text/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_golang.org_x_text_LICENSE
cp vendor/golang.org/x/time/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_golang.org_x_time_LICENSE
cp vendor/golang.org/x/tools/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_golang.org_x_tools_LICENSE
cp vendor/golang.org/x/xerrors/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_golang.org_x_xerrors_LICENSE
cp vendor/gonum.org/v1/gonum/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_gonum.org_v1_gonum_LICENSE
cp vendor/google.golang.org/api/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_google.golang.org_api_LICENSE
cp vendor/google.golang.org/api/googleapi/internal/uritemplates/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_google.golang.org_api_googleapi_internal_uritemplates_LICENSE
cp vendor/google.golang.org/appengine/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_google.golang.org_appengine_LICENSE
cp vendor/google.golang.org/genproto/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_google.golang.org_genproto_LICENSE
cp vendor/google.golang.org/grpc/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_google.golang.org_grpc_LICENSE
cp vendor/gopkg.in/DataDog/dd-trace-go.v1/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_gopkg.in_DataDog_dd-trace-go.v1_LICENSE
cp vendor/gopkg.in/DataDog/dd-trace-go.v1/LICENSE-3rdparty.csv %{buildroot}/usr/share/package-licenses/traefik/vendor_gopkg.in_DataDog_dd-trace-go.v1_LICENSE-3rdparty.csv
cp vendor/gopkg.in/fsnotify.v1/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_gopkg.in_fsnotify.v1_LICENSE
cp vendor/gopkg.in/inf.v0/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_gopkg.in_inf.v0_LICENSE
cp vendor/gopkg.in/ini.v1/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_gopkg.in_ini.v1_LICENSE
cp vendor/gopkg.in/ns1/ns1-go.v2/LICENSE.txt %{buildroot}/usr/share/package-licenses/traefik/vendor_gopkg.in_ns1_ns1-go.v2_LICENSE.txt
cp vendor/gopkg.in/resty.v1/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_gopkg.in_resty.v1_LICENSE
cp vendor/gopkg.in/square/go-jose.v2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_gopkg.in_square_go-jose.v2_LICENSE
cp vendor/gopkg.in/square/go-jose.v2/json/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_gopkg.in_square_go-jose.v2_json_LICENSE
cp vendor/gopkg.in/yaml.v2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_gopkg.in_yaml.v2_LICENSE
cp vendor/gopkg.in/yaml.v2/LICENSE.libyaml %{buildroot}/usr/share/package-licenses/traefik/vendor_gopkg.in_yaml.v2_LICENSE.libyaml
cp vendor/gopkg.in/yaml.v2/NOTICE %{buildroot}/usr/share/package-licenses/traefik/vendor_gopkg.in_yaml.v2_NOTICE
cp vendor/k8s.io/api/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_k8s.io_api_LICENSE
cp vendor/k8s.io/apimachinery/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_k8s.io_apimachinery_LICENSE
cp vendor/k8s.io/client-go/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_k8s.io_client-go_LICENSE
cp vendor/k8s.io/code-generator/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_k8s.io_code-generator_LICENSE
cp vendor/k8s.io/gengo/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_k8s.io_gengo_LICENSE
cp vendor/k8s.io/klog/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_k8s.io_klog_LICENSE
cp vendor/k8s.io/kube-openapi/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_k8s.io_kube-openapi_LICENSE
cp vendor/k8s.io/utils/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_k8s.io_utils_LICENSE
cp vendor/mvdan.cc/xurls/v2/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_mvdan.cc_xurls_v2_LICENSE
cp vendor/sigs.k8s.io/yaml/LICENSE %{buildroot}/usr/share/package-licenses/traefik/vendor_sigs.k8s.io_yaml_LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/traefik

%files data
%defattr(-,root,root,-)
/usr/share/traefik/traefik.sample.toml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/traefik/LICENSE.md
/usr/share/package-licenses/traefik/docs_content_assets_js_hljs_LICENSE
/usr/share/package-licenses/traefik/vendor_cloud.google.com_go_LICENSE
/usr/share/package-licenses/traefik/vendor_contrib.go.opencensus.io_exporter_ocagent_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_Azure_azure-sdk-for-go_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-ansiterm_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_adal_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_azure_auth_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_azure_cli_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_date_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_to_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_autorest_validation_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_logger_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_Azure_go-autorest_tracing_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_BurntSushi_toml_COPYING
/usr/share/package-licenses/traefik/vendor_github.com_ExpediaDotCom_haystack-client-go_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_Masterminds_goutils_LICENSE.txt
/usr/share/package-licenses/traefik/vendor_github.com_Masterminds_semver_LICENSE.txt
/usr/share/package-licenses/traefik/vendor_github.com_Masterminds_sprig_LICENSE.txt
/usr/share/package-licenses/traefik/vendor_github.com_Microsoft_go-winio_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_Microsoft_hcsshim_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_NYTimes_gziphandler_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_OpenDNS_vegadns2client_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_VividCortex_gohistogram_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_abbot_go-http-auth_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_abronan_valkeyrie_LICENSE.code
/usr/share/package-licenses/traefik/vendor_github.com_abronan_valkeyrie_LICENSE.docs
/usr/share/package-licenses/traefik/vendor_github.com_akamai_AkamaiOPEN-edgegrid-golang_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_aliyun_alibaba-cloud-sdk-go_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_aws_aws-sdk-go_LICENSE.txt
/usr/share/package-licenses/traefik/vendor_github.com_beorn7_perks_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_c0va23_go-proxyprotocol_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_cenkalti_backoff_v3_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_census-instrumentation_opencensus-proto_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_cloudflare_cloudflare-go_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_codahale_hdrhistogram_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_containerd_continuity_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_containous_alice_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_coreos_go-systemd_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_cpu_goacmedns_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_davecgh_go-spew_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_decker502_dnspod-go_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_dgrijalva_jwt-go_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_dimchansky_utfbom_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_dnsimple_dnsimple-go_LICENSE.txt
/usr/share/package-licenses/traefik/vendor_github.com_docker_cli_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_docker_cli_NOTICE
/usr/share/package-licenses/traefik/vendor_github.com_docker_distribution_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_docker_docker-credential-helpers_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_docker_docker_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_docker_docker_NOTICE
/usr/share/package-licenses/traefik/vendor_github.com_docker_docker_pkg_symlink_LICENSE.APACHE
/usr/share/package-licenses/traefik/vendor_github.com_docker_docker_pkg_symlink_LICENSE.BSD
/usr/share/package-licenses/traefik/vendor_github.com_docker_go-connections_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_docker_go-metrics_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_docker_go-metrics_LICENSE.docs
/usr/share/package-licenses/traefik/vendor_github.com_docker_go-units_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_docker_libcompose_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_eapache_channels_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_eapache_queue_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_elazarl_go-bindata-assetfs_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_evanphx_json-patch_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_exoscale_egoscale_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_fatih_structs_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_felixge_httpsnoop_LICENSE.txt
/usr/share/package-licenses/traefik/vendor_github.com_flynn_go-shlex_COPYING
/usr/share/package-licenses/traefik/vendor_github.com_gambol99_go-marathon_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_go-acme_lego_v3_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_go-check_check_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_go-errors_errors_LICENSE.MIT
/usr/share/package-licenses/traefik/vendor_github.com_go-ini_ini_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_go-kit_kit_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_go-logfmt_logfmt_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_gofrs_uuid_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_gogo_protobuf_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_golang_protobuf_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_google_go-cmp_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_google_go-github_v28_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_google_go-querystring_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_google_gofuzz_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_google_uuid_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_googleapis_gax-go_v2_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_googleapis_gnostic_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_gophercloud_gophercloud_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_gorilla_context_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_gorilla_mux_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_gorilla_websocket_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_gravitational_trace_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_grpc-ecosystem_grpc-gateway_LICENSE.txt
/usr/share/package-licenses/traefik/vendor_github.com_hashicorp_go-version_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_hashicorp_golang-lru_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_huandu_xstrings_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_iij_doapi_LICENSE.md
/usr/share/package-licenses/traefik/vendor_github.com_imdario_mergo_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_influxdata_influxdb1-client_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_instana_go-sensor_LICENSE.md
/usr/share/package-licenses/traefik/vendor_github.com_jmespath_go-jmespath_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_jonboulle_clockwork_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_json-iterator_go_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_kolo_xmlrpc_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_konsorten_go-windows-terminal-sequences_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_labbsr0x_bindman-dns-webhook_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_labbsr0x_goh_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_libkermit_compose_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_libkermit_docker-check_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_libkermit_docker_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_linode_linodego_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_looplab_fsm_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_mailgun_minheap_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_mailgun_multibuf_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_mailgun_timetools_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_mailgun_ttlmap_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_matttproud_golang_protobuf_extensions_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_miekg_dns_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_mitchellh_copystructure_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_mitchellh_go-homedir_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_mitchellh_hashstructure_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_mitchellh_mapstructure_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_mitchellh_reflectwalk_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_modern-go_concurrent_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_modern-go_reflect2_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_morikuni_aec_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_namedotcom_go_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_nrdcg_auroradns_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_nrdcg_goinwx_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_nrdcg_namesilo_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_opencontainers_go-digest_LICENSE.code
/usr/share/package-licenses/traefik/vendor_github.com_opencontainers_go-digest_LICENSE.docs
/usr/share/package-licenses/traefik/vendor_github.com_opencontainers_image-spec_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_opencontainers_runc_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_opentracing-contrib_go-observer_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_opentracing_basictracer-go_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_opentracing_opentracing-go_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_openzipkin-contrib_zipkin-go-opentracing_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_openzipkin_zipkin-go_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_oracle_oci-go-sdk_LICENSE.txt
/usr/share/package-licenses/traefik/vendor_github.com_ovh_go-ovh_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_patrickmn_go-cache_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_philhofer_fwd_LICENSE.md
/usr/share/package-licenses/traefik/vendor_github.com_pkg_errors_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_pmezard_go-difflib_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_prometheus_client_golang_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_prometheus_client_golang_NOTICE
/usr/share/package-licenses/traefik/vendor_github.com_prometheus_client_model_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_prometheus_common_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_prometheus_procfs_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_sacloud_libsacloud_LICENSE.txt
/usr/share/package-licenses/traefik/vendor_github.com_sirupsen_logrus_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_spf13_pflag_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_stretchr_objx_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_stretchr_testify_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_stvp_go-udp-testing_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_timewasted_linode_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_tinylib_msgp_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_transip_gotransip_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_uber_jaeger-client-go_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_uber_jaeger-lib_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_unrolled_render_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_unrolled_secure_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_vdemeester_shakers_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_vulcand_oxy_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_vulcand_predicate_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_vultr_govultr_LICENSE
/usr/share/package-licenses/traefik/vendor_github.com_xeipuuv_gojsonpointer_LICENSE-APACHE-2.0.txt
/usr/share/package-licenses/traefik/vendor_github.com_xeipuuv_gojsonreference_LICENSE-APACHE-2.0.txt
/usr/share/package-licenses/traefik/vendor_github.com_xeipuuv_gojsonschema_LICENSE-APACHE-2.0.txt
/usr/share/package-licenses/traefik/vendor_go.opencensus.io_LICENSE
/usr/share/package-licenses/traefik/vendor_go.uber.org_ratelimit_LICENSE
/usr/share/package-licenses/traefik/vendor_golang.org_x_crypto_LICENSE
/usr/share/package-licenses/traefik/vendor_golang.org_x_net_LICENSE
/usr/share/package-licenses/traefik/vendor_golang.org_x_oauth2_LICENSE
/usr/share/package-licenses/traefik/vendor_golang.org_x_sync_LICENSE
/usr/share/package-licenses/traefik/vendor_golang.org_x_sys_LICENSE
/usr/share/package-licenses/traefik/vendor_golang.org_x_text_LICENSE
/usr/share/package-licenses/traefik/vendor_golang.org_x_time_LICENSE
/usr/share/package-licenses/traefik/vendor_golang.org_x_tools_LICENSE
/usr/share/package-licenses/traefik/vendor_golang.org_x_xerrors_LICENSE
/usr/share/package-licenses/traefik/vendor_gonum.org_v1_gonum_LICENSE
/usr/share/package-licenses/traefik/vendor_google.golang.org_api_LICENSE
/usr/share/package-licenses/traefik/vendor_google.golang.org_api_googleapi_internal_uritemplates_LICENSE
/usr/share/package-licenses/traefik/vendor_google.golang.org_appengine_LICENSE
/usr/share/package-licenses/traefik/vendor_google.golang.org_genproto_LICENSE
/usr/share/package-licenses/traefik/vendor_google.golang.org_grpc_LICENSE
/usr/share/package-licenses/traefik/vendor_gopkg.in_DataDog_dd-trace-go.v1_LICENSE
/usr/share/package-licenses/traefik/vendor_gopkg.in_DataDog_dd-trace-go.v1_LICENSE-3rdparty.csv
/usr/share/package-licenses/traefik/vendor_gopkg.in_fsnotify.v1_LICENSE
/usr/share/package-licenses/traefik/vendor_gopkg.in_inf.v0_LICENSE
/usr/share/package-licenses/traefik/vendor_gopkg.in_ini.v1_LICENSE
/usr/share/package-licenses/traefik/vendor_gopkg.in_ns1_ns1-go.v2_LICENSE.txt
/usr/share/package-licenses/traefik/vendor_gopkg.in_resty.v1_LICENSE
/usr/share/package-licenses/traefik/vendor_gopkg.in_square_go-jose.v2_LICENSE
/usr/share/package-licenses/traefik/vendor_gopkg.in_square_go-jose.v2_json_LICENSE
/usr/share/package-licenses/traefik/vendor_gopkg.in_yaml.v2_LICENSE
/usr/share/package-licenses/traefik/vendor_gopkg.in_yaml.v2_LICENSE.libyaml
/usr/share/package-licenses/traefik/vendor_gopkg.in_yaml.v2_NOTICE
/usr/share/package-licenses/traefik/vendor_k8s.io_api_LICENSE
/usr/share/package-licenses/traefik/vendor_k8s.io_apimachinery_LICENSE
/usr/share/package-licenses/traefik/vendor_k8s.io_client-go_LICENSE
/usr/share/package-licenses/traefik/vendor_k8s.io_code-generator_LICENSE
/usr/share/package-licenses/traefik/vendor_k8s.io_gengo_LICENSE
/usr/share/package-licenses/traefik/vendor_k8s.io_klog_LICENSE
/usr/share/package-licenses/traefik/vendor_k8s.io_kube-openapi_LICENSE
/usr/share/package-licenses/traefik/vendor_k8s.io_utils_LICENSE
/usr/share/package-licenses/traefik/vendor_mvdan.cc_xurls_v2_LICENSE
/usr/share/package-licenses/traefik/vendor_sigs.k8s.io_yaml_LICENSE

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/traefik.service
